name: papylio
channels:
- conda-forge
dependencies:
- python=3.14
- numpy
- matplotlib-base
- matplotlib-venn
- pathlib2
- opencv
- tabulate
- scipy
- scikit-image
- scikit-learn
- pyyaml
- pandas
- seaborn
- openpyxl
- sphinx=5
- sphinx-book-theme
- nd2reader
- shapely
- xarray
- netcdf4
- h5netcdf
- dask
- dask-image
- bottleneck
- tifffile
- tqdm
- pyside6
- pytest
- pytest-datadir
- numba
- pomegranate=1
- nbsphinx
- notebook
- jupyterlab-mathjax2
- matchpoint=1.1
- objectlist=1.0
- git
- perl
- setuptools >=61.0.0
- setuptools-scm >=8
#- bioconda::logomaker=0.8
# Logomaker has a matplotlib dependency, which installs PyQt
# So please install manually if needed using
# "conda install bioconda::logomaker=0.8 -c conda-forge --no-deps"
